name: sharaka
description: "شراكة - منصة استثمار جماعي بالأسهم للمشاريع الريادية في سلطنة عُمان والخليج"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Backend
  supabase_flutter: ^2.5.6

  # State management
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^14.2.0

  # UI
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.2.0+3

  # Forms & files
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  intl: ^0.20.2

  # Utils
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
