import '../models/project_model.dart';

/// بيانات تجريبية مؤقتة لعرض الشاشات — يتم استبدالها لاحقاً باستعلامات Supabase الفعلية
final List<InvestmentProject> mockProjects = [
  InvestmentProject(
    id: '1',
    ownerId: 'owner1',
    title: 'مزرعة عمودية ذكية - مسقط',
    sector: 'زراعة',
    country: 'عُمان',
    city: 'مسقط',
    shortDescription: 'مزرعة عمودية بتقنية الزراعة المائية داخل مستودعات صناعية مُهيّأة',
    fullDescription:
        'مشروع مزرعة عمودية يعتمد تقنية الزراعة المائية (Hydroponics) لإنتاج خضروات ورقية طازجة على مدار السنة، '
        'باستخدام مساحة أقل بـ90٪ من الزراعة التقليدية واستهلاك مياه أقل بـ95٪. المشروع مرخّص ولديه عقود توريد '
        'مبدئية مع 3 سلاسل سوبرماركت محلية.',
    coverImageUrl: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=800',
    targetAmount: 150000,
    raisedAmount: 96000,
    sharePrice: 50,
    totalShares: 3000,
    soldShares: 1920,
    minInvestment: 250,
    expectedAnnualReturn: 18,
    fundingDeadline: DateTime.now().add(const Duration(days: 22)),
    status: ProjectStatus.funding,
    investorsCount: 84,
    createdAt: DateTime.now().subtract(const Duration(days: 10)),
  ),
  InvestmentProject(
    id: '2',
    ownerId: 'owner2',
    title: 'تطبيق توصيل صيدليات - صحار',
    sector: 'تقنية',
    country: 'عُمان',
    city: 'صحار',
    shortDescription: 'منصة توصيل أدوية بين الصيدليات والمنازل خلال 30 دقيقة',
    fullDescription:
        'تطبيق يربط الصيدليات المرخّصة بالمستخدمين لتوصيل الأدوية والمستلزمات الطبية، مع نظام تحقق من الوصفات '
        'الطبية إلكترونياً وشراكات مع 12 صيدلية حتى الآن.',
    coverImageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800',
    targetAmount: 80000,
    raisedAmount: 34000,
    sharePrice: 20,
    totalShares: 4000,
    soldShares: 1700,
    minInvestment: 100,
    expectedAnnualReturn: 24,
    fundingDeadline: DateTime.now().add(const Duration(days: 40)),
    status: ProjectStatus.funding,
    investorsCount: 156,
    createdAt: DateTime.now().subtract(const Duration(days: 5)),
  ),
  InvestmentProject(
    id: '3',
    ownerId: 'owner3',
    title: 'مجمع شقق فندقية - صلالة',
    sector: 'عقارات',
    country: 'عُمان',
    city: 'صلالة',
    shortDescription: 'وحدات سكنية فندقية بموسم الخريف السياحي في صلالة',
    fullDescription:
        'تطوير مجمع من 18 وحدة سكنية فندقية قرب الواجهة السياحية بصلالة، يستهدف موسم الخريف (يوليو-سبتمبر) '
        'ذو الإقبال السياحي الكثيف، بعائد إيجاري متوقع مرتفع خلال الموسم.',
    coverImageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
    targetAmount: 400000,
    raisedAmount: 168000,
    sharePrice: 200,
    totalShares: 2000,
    soldShares: 840,
    minInvestment: 400,
    expectedAnnualReturn: 15,
    fundingDeadline: DateTime.now().add(const Duration(days: 60)),
    status: ProjectStatus.funding,
    investorsCount: 61,
    createdAt: DateTime.now().subtract(const Duration(days: 18)),
  ),
  InvestmentProject(
    id: '4',
    ownerId: 'owner4',
    title: 'مصنع تعبئة تمور - نزوى',
    sector: 'صناعة',
    country: 'عُمان',
    city: 'نزوى',
    shortDescription: 'خط إنتاج آلي لتعبئة وتصدير التمور العُمانية',
    fullDescription:
        'إنشاء خط تعبئة وتغليف آلي للتمور العُمانية عالية الجودة بهدف التصدير لأسواق الخليج وأوروبا، '
        'مع شهادات جودة غذائية دولية قيد الاستخراج.',
    coverImageUrl: 'https://images.unsplash.com/photo-1609951651556-5334e2706168?w=800',
    targetAmount: 220000,
    raisedAmount: 55000,
    sharePrice: 100,
    totalShares: 2200,
    soldShares: 550,
    minInvestment: 300,
    expectedAnnualReturn: 20,
    fundingDeadline: DateTime.now().add(const Duration(days: 35)),
    status: ProjectStatus.funding,
    investorsCount: 39,
    createdAt: DateTime.now().subtract(const Duration(days: 3)),
  ),
];
